//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASITHmsWpf.ASITHmsService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ASITHmsService1.IASITHmsService")]
    public interface IASITHmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetData", ReplyAction="http://tempuri.org/IASITHmsService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetData", ReplyAction="http://tempuri.org/IASITHmsService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataSetResult", ReplyAction="http://tempuri.org/IASITHmsService/GetDataSetResultResponse")]
        System.Data.DataSet GetDataSetResult(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataSetResult", ReplyAction="http://tempuri.org/IASITHmsService/GetDataSetResultResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetResultAsync(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataSetResultWeb", ReplyAction="http://tempuri.org/IASITHmsService/GetDataSetResultWebResponse")]
        System.Data.DataSet GetDataSetResultWeb(
                    string _comCod, 
                    string _ProcName, 
                    string _ProcID, 
                    System.Data.DataSet _parmXml01, 
                    System.Data.DataSet _parmXml02, 
                    byte[] _parmBin01, 
                    string _parm01, 
                    string _parm02, 
                    string _parm03, 
                    string _parm04, 
                    string _parm05, 
                    string _parm06, 
                    string _parm07, 
                    string _parm08, 
                    string _parm09, 
                    string _parm10, 
                    string _parm11, 
                    string _parm12, 
                    string _parm13, 
                    string _parm14, 
                    string _parm15, 
                    string _parm16, 
                    string _parm17, 
                    string _parm18, 
                    string _parm19, 
                    string _parm20, 
                    string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataSetResultWeb", ReplyAction="http://tempuri.org/IASITHmsService/GetDataSetResultWebResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetResultWebAsync(
                    string _comCod, 
                    string _ProcName, 
                    string _ProcID, 
                    System.Data.DataSet _parmXml01, 
                    System.Data.DataSet _parmXml02, 
                    byte[] _parmBin01, 
                    string _parm01, 
                    string _parm02, 
                    string _parm03, 
                    string _parm04, 
                    string _parm05, 
                    string _parm06, 
                    string _parm07, 
                    string _parm08, 
                    string _parm09, 
                    string _parm10, 
                    string _parm11, 
                    string _parm12, 
                    string _parm13, 
                    string _parm14, 
                    string _parm15, 
                    string _parm16, 
                    string _parm17, 
                    string _parm18, 
                    string _parm19, 
                    string _parm20, 
                    string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetXmlStrResult", ReplyAction="http://tempuri.org/IASITHmsService/GetXmlStrResultResponse")]
        string GetXmlStrResult(string XmlPap1, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetXmlStrResult", ReplyAction="http://tempuri.org/IASITHmsService/GetXmlStrResultResponse")]
        System.Threading.Tasks.Task<string> GetXmlStrResultAsync(string XmlPap1, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetJsonStrResult", ReplyAction="http://tempuri.org/IASITHmsService/GetJsonStrResultResponse")]
        string GetJsonStrResult(string JsonPap1, string parmXml01DsName, string parmXml02DsName, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetJsonStrResult", ReplyAction="http://tempuri.org/IASITHmsService/GetJsonStrResultResponse")]
        System.Threading.Tasks.Task<string> GetJsonStrResultAsync(string JsonPap1, string parmXml01DsName, string parmXml02DsName, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataSetNonQuerySQL", ReplyAction="http://tempuri.org/IASITHmsService/GetDataSetNonQuerySQLResponse")]
        System.Data.DataSet GetDataSetNonQuerySQL(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataSetNonQuerySQL", ReplyAction="http://tempuri.org/IASITHmsService/GetDataSetNonQuerySQLResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetNonQuerySQLAsync(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IASITHmsService/GetDataUsingDataContractResponse")]
        ASITHmsWpf.ASITHmsService1.CompositeType GetDataUsingDataContract(ASITHmsWpf.ASITHmsService1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASITHmsService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IASITHmsService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ASITHmsWpf.ASITHmsService1.CompositeType> GetDataUsingDataContractAsync(ASITHmsWpf.ASITHmsService1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IASITHmsServiceChannel : ASITHmsWpf.ASITHmsService1.IASITHmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ASITHmsServiceClient : System.ServiceModel.ClientBase<ASITHmsWpf.ASITHmsService1.IASITHmsService>, ASITHmsWpf.ASITHmsService1.IASITHmsService {
        
        public ASITHmsServiceClient() {
        }
        
        public ASITHmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ASITHmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASITHmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASITHmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Data.DataSet GetDataSetResult(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1) {
            return base.Channel.GetDataSetResult(pap1, comcod1);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetResultAsync(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1) {
            return base.Channel.GetDataSetResultAsync(pap1, comcod1);
        }
        
        public System.Data.DataSet GetDataSetResultWeb(
                    string _comCod, 
                    string _ProcName, 
                    string _ProcID, 
                    System.Data.DataSet _parmXml01, 
                    System.Data.DataSet _parmXml02, 
                    byte[] _parmBin01, 
                    string _parm01, 
                    string _parm02, 
                    string _parm03, 
                    string _parm04, 
                    string _parm05, 
                    string _parm06, 
                    string _parm07, 
                    string _parm08, 
                    string _parm09, 
                    string _parm10, 
                    string _parm11, 
                    string _parm12, 
                    string _parm13, 
                    string _parm14, 
                    string _parm15, 
                    string _parm16, 
                    string _parm17, 
                    string _parm18, 
                    string _parm19, 
                    string _parm20, 
                    string comcod1) {
            return base.Channel.GetDataSetResultWeb(_comCod, _ProcName, _ProcID, _parmXml01, _parmXml02, _parmBin01, _parm01, _parm02, _parm03, _parm04, _parm05, _parm06, _parm07, _parm08, _parm09, _parm10, _parm11, _parm12, _parm13, _parm14, _parm15, _parm16, _parm17, _parm18, _parm19, _parm20, comcod1);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetResultWebAsync(
                    string _comCod, 
                    string _ProcName, 
                    string _ProcID, 
                    System.Data.DataSet _parmXml01, 
                    System.Data.DataSet _parmXml02, 
                    byte[] _parmBin01, 
                    string _parm01, 
                    string _parm02, 
                    string _parm03, 
                    string _parm04, 
                    string _parm05, 
                    string _parm06, 
                    string _parm07, 
                    string _parm08, 
                    string _parm09, 
                    string _parm10, 
                    string _parm11, 
                    string _parm12, 
                    string _parm13, 
                    string _parm14, 
                    string _parm15, 
                    string _parm16, 
                    string _parm17, 
                    string _parm18, 
                    string _parm19, 
                    string _parm20, 
                    string comcod1) {
            return base.Channel.GetDataSetResultWebAsync(_comCod, _ProcName, _ProcID, _parmXml01, _parmXml02, _parmBin01, _parm01, _parm02, _parm03, _parm04, _parm05, _parm06, _parm07, _parm08, _parm09, _parm10, _parm11, _parm12, _parm13, _parm14, _parm15, _parm16, _parm17, _parm18, _parm19, _parm20, comcod1);
        }
        
        public string GetXmlStrResult(string XmlPap1, string comcod1) {
            return base.Channel.GetXmlStrResult(XmlPap1, comcod1);
        }
        
        public System.Threading.Tasks.Task<string> GetXmlStrResultAsync(string XmlPap1, string comcod1) {
            return base.Channel.GetXmlStrResultAsync(XmlPap1, comcod1);
        }
        
        public string GetJsonStrResult(string JsonPap1, string parmXml01DsName, string parmXml02DsName, string comcod1) {
            return base.Channel.GetJsonStrResult(JsonPap1, parmXml01DsName, parmXml02DsName, comcod1);
        }
        
        public System.Threading.Tasks.Task<string> GetJsonStrResultAsync(string JsonPap1, string parmXml01DsName, string parmXml02DsName, string comcod1) {
            return base.Channel.GetJsonStrResultAsync(JsonPap1, parmXml01DsName, parmXml02DsName, comcod1);
        }
        
        public System.Data.DataSet GetDataSetNonQuerySQL(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1) {
            return base.Channel.GetDataSetNonQuerySQL(pap1, comcod1);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetNonQuerySQLAsync(ASITFunLib.ASITFunParams.ProcessAccessParams pap1, string comcod1) {
            return base.Channel.GetDataSetNonQuerySQLAsync(pap1, comcod1);
        }
        
        public ASITHmsWpf.ASITHmsService1.CompositeType GetDataUsingDataContract(ASITHmsWpf.ASITHmsService1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ASITHmsWpf.ASITHmsService1.CompositeType> GetDataUsingDataContractAsync(ASITHmsWpf.ASITHmsService1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
